name: schedule check and dispatch
on:
  workflow_dispatch:
    name: manula trigger
  schedule:
    - cron: "* 1 * * *"

jobs:
  populate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: set-matrix
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          ./scripts/check-updates.sh

  call-update-and-rebuild:
    needs: populate-matrix
    strategy:
      matrix: ${{fromJson(needs.populate-matrix.outputs.matrix)}}
    uses: ./.github/workflows/update-and-rebuild.yaml
    with:
      osmosis_rev: ${{ matrix.target }}
